### ISSUE TITLE
Water effects can replace land 

### ISSUE THREAD

**Issue by Alduin1996** [SleepKiller/swbfii-shaderpatch#25] opened 2018-08-12 15:17 UTC
https://cdn.discordapp.com/attachments/449701008294019073/478198076041986058/Star_Wars_Battlefront_II_2005_Screenshot_2018.08.12_-_14.45.01.28.png

When playing on Kashyyyk while standing on the platforms there is a chance the water will appear in places it is not supposed to. I have tested the map without the SP and it works as intended. Which is a shame because the shader patch is a good mod. 

I am using Kashyyyk rezzed by HF if it is any help

**Comment by SleepKiller** [comment] 2018-08-13 08:14
Thanks for letting me know! I think I recall HarrisonFog telling me about this a while back and I let it slip my mind. I believe the problem is being caused by the near scene and far scene not being blended properly so I have pretty good idea of what could be causing the problem, I'll try to have it fixed in the next release.

**Comment by SleepKiller** [comment] 2018-08-18 05:59
It's always nice to hear positive feedback, thanks! Adding an option to switch off the new water shader incase looks off on someone's machine (or just looks wrong on their favourite map) sounds like a good idea. It's a bit more work than I had time for today but it's definitely something that'd be nice for the future.

As for this itself bug it's been fixed by eca164e6cdeb7af3cb74201cd45906dec9b012eb and a new release is out with the fix in it.

**Closed by SleepKiller** 2018-08-18 05:59 UTC
Labels: bug
